@Gateway.API_HostAddress = http://localhost:5070

###
POST {{Gateway.API_HostAddress}}/gateway/roles
Content-Type: application/json

{
  "RoleName": "Teacher"
}

###
POST {{Gateway.API_HostAddress}}/gateway/auth/login
Content-Type: application/json

{
  "Email": "admin@app.com",
  "Password": "Admin@123"
}

###
GET {{Gateway.API_HostAddress}}/gateway/auditlogs